An example using hdf5 references (#396)
BlueBrain/HighFive pull request #397
Opened 2021-01-16 10:16 UTC by plusangel

I included an example to demonstrate how references work in HighFive. PR suggested by @tdegeus 

Thank you guys

2021-01-26 15:05 UTC, tdegeus reviewed
I'm probably not the best person to review, because I don't actually know references in HDF5. That being said, it didn't become clear from this example either... Some line of text would surely help there: describe what the example is doing in a few lines of comment somewhere. 

Where I really got lost though is with the `  std::vector<Reference>`. The question is: Are reference in HDF5 something similar to those in C++? If so, wouldn't it be easier to (also) have a basic example with one reference?

2021-03-17 21:46 UTC, ohm314 requested changes
Hi @plusangel, sorry for taking so long to review this. Overall the example is small enough and a good idea to add. We actually have in the unit tests already something very similar (but I understand that looking at test cases is a pain, especially when you're just getting into the library).
@tdegeus gave already some very good feedback. Could I ask you to please implement his and my suggestions into an additional patch. I"ll try to then re-review fairly quickly and have this merged!
Here's the test case, for reference: https://github.com/BlueBrain/HighFive/blob/master/tests/unit/tests_high_five_base.cpp#L1587

2021-03-17 21:46 UTC, ohm314 commented on src/examples/read_write_vector_dataset_references.cpp
> +using namespace HighFive;
I agree, please remove the using namespace declaration. As @tdegeus said, this just makes things less clear and is generally a bad practice that should be avoided.

2021-03-17 21:46 UTC, ohm314 commented on src/examples/read_write_vector_dataset_references.cpp
> +const std::string SOURCE_INT_DATASET_NAME("source_dateset");
```suggestion
const std::string SOURCE_INT_DATASET_NAME("source_dataset");
```

2021-03-17 21:46 UTC, ohm314 commented on src/examples/read_write_vector_dataset_references.cpp
> +const std::string REFERENCE_DATASET_NAME("reference_dateset");
I don't mind either. Defining the strings doesn't hurt, but doesn't add much. Either is fine.

2021-03-17 21:46 UTC, ohm314 commented on src/examples/read_write_vector_dataset_references.cpp
> +// create a dataset 1D from a vector of string
```suggestion
// create a dataset 1D from a vector of int
```

2021-03-17 21:46 UTC, ohm314 commented on src/examples/read_write_vector_dataset_references.cpp
> +    Group group = file.createGroup("a_group");
why do you define const strings for the file name and dataset names, but not the group. I would be consistent, whatever you choose.

2021-03-17 21:46 UTC, ohm314 commented on src/examples/read_write_vector_dataset_references.cpp
> +    // in similar fashion, we store as dataset the reference that we want
```suggestion
    // in similar fashion, we store as dataset the vector of references that we want
```

2021-03-19 17:48 UTC, plusangel commented
Thank you both for your valuable comments and your time to review it. I think I catch them all. Keep up the good work. Thank you!

2021-03-25 22:58 UTC, ferdonline requested changes

2021-03-25 22:58 UTC, ferdonline commented on src/examples/read_write_vector_dataset_references.cpp
> + *  Copyright (c), 2017, Adrien Devresse
```suggestion
 *  Copyright (c), 2021 Blue Brain Project - EPFL
```

2021-03-25 22:58 UTC, ferdonline commented on src/examples/read_write_vector_dataset_references.cpp
> +
```suggestion
```

2021-03-25 22:58 UTC, ferdonline commented on src/examples/read_write_vector_dataset_references.cpp
> +                                                  HighFive::File::Truncate);
```suggestion
    HighFive::File file("dataset_integer.h5", HighFive::File::Overwrite);
```

2021-03-25 22:58 UTC, ferdonline commented on src/examples/read_write_vector_dataset_references.cpp
> +    }
```suggestion
    std::vector<int> data(20);
    std::iota(data.begin(), data.end(), 0);
```

2021-03-25 22:58 UTC, ferdonline commented on src/examples/read_write_vector_dataset_references.cpp
> +    dataset.write(data);
```suggestion
    auto dataset = group.createDataSet("source_dataset", data);
```

2021-03-25 22:58 UTC, ferdonline commented on src/examples/read_write_vector_dataset_references.cpp
> +}
```suggestion
}

```

2021-03-31 12:08 UTC, ferdonline commented
@plusangel Do you have an estimate on when you could address this PR suggestions?

2021-03-31 15:03 UTC, plusangel commented
Sorry for the delay @ferdonline. Done :)

2021-03-31 16:00 UTC, ferdonline submitted a review, later dismissed

2021-03-31 16:06 UTC, tdegeus approved these changes

2021-03-31 16:08 UTC, ohm314 approved these changes
lgtm

2021-03-31 19:22 UTC, merged