Code fixes and website improvements
BlueBrain/HighFive pull request #555
Opened 2022-04-06 20:51 UTC by ohm314

We push here a few more fixes and additions to finalize the website for the poster.

The version that is currently deployed on gh-pages is here: https://go.epfl.ch/hi5

2022-04-07 11:53 UTC, matz-e requested changes

2022-04-07 11:53 UTC, matz-e commented on include/highfive/H5PropertyList.hpp
> +    friend GroupCreateProps;
```suggestion
```

2022-04-08 11:04 UTC, matz-e submitted a review, later dismissed

2022-04-08 11:48 UTC, matz-e approved these changes

2022-04-08 11:49 UTC, ohm314 commented
Let's merge this now so it's up to date when submitting poster. We can always add a bit more content later.

2022-04-08 11:51 UTC, matz-e submitted a review, later dismissed

2022-04-08 12:55 UTC, alkino approved these changes

2022-04-08 13:05 UTC, merged