Sliced io
BlueBrain/HighFive pull request #602
Opened 2022-08-19 15:30 UTC by nathan-mxr

**Description**

Implemented load_part and dump_extend for XTensor data types.

This requires a new public load API that accepts a vector of sizes as a parameter, to define how many elements should be read in each dimension.

Fixes #596 

**How to test this?**

Have added tests to tests_high_five_easy.cpp to exercise this feature:
- Loading a single value into an XTensor/XArray (no sizes argument)
- Loading a subset of a dataset into an XTensor/XArray (normal sizes argument)
- Load a subset that exceeds the bounds of a dataset into an XTensor/XArray (index + size > dataset dimension)
- Dumping an XTensor/XArray/XView to a non-zero index of a Dataset. 

```bash
cmake ..
make -j8
make test
```

**Test System**
 - OS: Ubuntu 22.04
 - Compiler: gcc 11.2.0
 - Dependency versions: hdf5 1.12

2022-08-25 12:53 UTC, tdegeus commented
Thanks! Before diving into it, could you briefly discuss here what the API would like like? Along this lines should we consider something like the API for `xt::view` ?

2022-08-25 13:15 UTC, nathan-mxr commented
> Thanks! Before diving into it, could you briefly discuss here what the API would like like? Along this lines should we consider something like the API for `xt::view` ?

Hi Tom, the new H5_Easy API method for `load` can be found in the change to `include/highfive/h5easy_bits/H5Easy_public.hpp`. 

It is an extension of the previously existing prototype, which had arguments:
```
const File& file, 
const std::string& path, 
const std::vector<size_t>& idx
```
allowing only a single item of the dataset to be addressed.

The new API has arguments:
```
const File& file,  
const std::string& path, 
const std::vector<size_t>& idx,
const std::vector<size_t>& sizes
```
Where idx and sizes must have the same number of elements. idx indicates where the first element of the slice can be found, and sizes denotes how many elements in each dimension should be read from the dataset. This is similar to the H5 hyperslab selection arguments `offset` and `count`: https://bluebrain.github.io/HighFive/class_high_five_1_1_slice_traits.html#a6a76a20247d0e8f8629b81c17425d73c
Hyperslab selection also allows for "stride" and "block" vectors, that I have not implemented.

I think the implementation for `xt::view` may be slightly more complicated, as (if I understand correctly) `xt::view::data()` will return a pointer to the entire underlying data structure, so can't be trivially used with `write_raw()` and `read()`.

2022-09-20 09:00 UTC, tdegeus requested changes
Sorry for my late review. In general I think this is very nice. Thanks a lot! What I really not like is the automatic resizing of the load slice (see above). For the rest, I had a worry, but I think that it is unjustified (see above). 

Then, I think that the test would be a lot cleaner without the automatic type-cast, which tests a feature of xtensor and not of highfive.

2023-02-15 14:43 UTC, alkino commented
As there is no update since 5 months, I close it. If someone want to fix / continue this PR, we can reopen it.

2023-02-15 14:43 UTC, closed without merging